version: "3.8"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env.prod
    expose:
      - "5432"
  web:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
      target: django
#      args:
#        - http_proxy=...
#        - https_proxy=...
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.prod
    environment:
      WAIT_HOSTS: db:5432
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
      target: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_db: