version: "3.8"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env.dev
    expose:
      - "5432"
  backend:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
      target: django
#      args:
#        - http_proxy=...
#        - https_proxy=...
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.dev
    environment:
      WAIT_HOSTS: db:5432
    volumes:
      - .:/code
      - /code/frontend/
      - media:/media
      #- staticfiles:/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
      target: node
#      args:
#        - http_proxy=...
#        - https_proxy=...
    volumes:
      - ./frontend:/frontend/
      - ./templates:/frontend/build/templates/
      - /frontend/build
      - /frontend/node_modules/
    ports:
      - "8080:8080"
    env_file:
      - .env.dev

volumes:
  postgres_db:
  media: