version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
      target: django
    command: gunicorn django_settings.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
  nginx:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
      target: nginx
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_db: