version: "3.8"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env.prod
    expose:
      - "5432"
  web:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
      target: django
#      args:
#        - http_proxy=...
#        - https_proxy=...
    # workaround to add staticfiles/media to volume for nginx
    command: bash -c '/wait && cp -r /staticfiles/* /staticfiles_volume/; python manage.py migrate; gunicorn django_settings.wsgi:application --bind 0.0.0.0:8000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.prod
    environment:
      WAIT_HOSTS: db:5432
    volumes:
      - staticfiles:/staticfiles_volume
      - media:/media
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/staticfiles
      - media:/media
    depends_on:
      - web

volumes:
  postgres_db:
  staticfiles:
  media: