version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    command: ./entrypoint.sh
    volumes:
      - staticfiles:/code/staticfiles
    env_file:
      - ./.env.prod
    expose:
      - "8000"
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    #    environment:
    #      - POSTGRES_USER=postgres
    #      - POSTGRES_PASSWORD=postgres
    #      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/staticfiles

volumes:
  postgres_db:
  staticfiles: