version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    env_file:
      - ./.env.dev
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
  backend:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /code/frontend/
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    extends:
      service: web
    working_dir: /code/frontend
    command: npm run serve
    volumes:
      - ./frontend:/code/frontend
      - /code/frontend/node_modules/
    ports:
      - "8080:8080"

volumes:
  postgres_db: